server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: onboarding-assignment
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://${DB_HOST}/onboarding
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}
      timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: method
  api-docs:
    path: /api-docs

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate: WARN
    com.example.onboardingassignment: INFO
    # JWT 관련 로그는 WARN 레벨로 설정
    com.example.onboardingassignment.security: WARN
    # SQL 로그는 INFO 레벨로 설정
    org.hibernate.SQL: INFO
    org.hibernate.type: WARN

jwt:
  secret.key: ${JWT_SECRET_KEY}

owner:
  token: ${OWNER_TOKEN}
